curused: "Dev"
Dev:
  level: 0
  fail_url: ""
  error_url: ""
  warn_url: "https://open.feishu.cn/open-apis/bot/v2/hook/7033a584-ce85-4eea-ae9d-fe1f5589ab59"
Pro:
  level: 1
  fail_url: ""
  error_url: ""
  warn_url: "https://open.feishu.cn/open-apis/bot/v2/hook/7033a584-ce85-4eea-ae9d-fe1f5589ab59"
Pre:
  level: 0
  fail_url: ""
  error_url: ""
  warn_url: "https://open.feishu.cn/open-apis/bot/v2/hook/7033a584-ce85-4eea-ae9d-fe1f5589ab59"