curused: Dev
Dev:
  version: 1
  gcp_attr:
    - name: dsp_bucket
      project: blueturbo
      bucket: blueturbo_dsp_logs_sg/account_token
Pro:
  version: 1
  gcp_attr:
    - name: dsp_bucket
      project: blueturbo
      bucket: blueturbo_dsp_logs_sg/account_token
Pre: 
Test: 