curused: Dev
Dev:
  version: 1
  cloud_acc:
    - name: event_redis
      account_email: 120671665411-compute@developer.gserviceaccount.com
Pro:
  version: 1
  cloud_acc:
    - name: event_redis
      account_email: 120671665411-compute@developer.gserviceaccount.com
Pre:
Test: